export const tests = [
  { id:'hb', name:'혈색소(Hb)', unit:'g/dL', allowedMin:3, allowedMax:25, step:0.1, genderRequired:true, ageRequired:false, reverse:false, normalRange:{male:[13.0,16.5], female:[12.0,15.5]}, redFlag:{low:8, maleHigh:18, femaleHigh:16}, descriptions:{normal:'산소를 나르는 힘이 정상 범위에 있어요.\n현재 수치는 무난한 편입니다.', high:'정상 범위보다 다소 높아요.\n검사지와 최근 컨디션을 함께 확인해보세요.', low:'정상 범위보다 다소 낮아요.\n어지러움이나 피로가 있으면 상담을 권해요.', redFlag:'빠른 시일 내 진료를 받아보시는 것을 권해드려요.\n검사지 수치를 다시 확인해주세요.'}, plainExplanation:'몸속 산소를 나르는 트럭입니다. 낮으면 어지럽고 쉽게 피로해집니다.'},
  { id:'wbc', name:'백혈구(WBC)', unit:'/μL', allowedMin:100, allowedMax:100000, step:1, genderRequired:false, ageRequired:false, reverse:false, normalRange:{default:[4000,10000]}, redFlag:{low:2000, high:30000}, descriptions:{normal:'몸을 지키는 세포 수가 정상 범위에 있어요.', high:'정상 범위보다 다소 높아요.\n최근 감기나 염증 반응 뒤에 오를 수 있어요.', low:'정상 범위보다 다소 낮아요.\n반복되면 병원 상담을 권장해요.', redFlag:'면역 관련 확인이 필요할 수 있어요.\n빠른 시일 내 진료를 권해요.'}, plainExplanation:'세균이나 바이러스와 싸우는 몸속 군대입니다.'},
  { id:'platelet', name:'혈소판', unit:'×10³/μL', allowedMin:1, allowedMax:2000, step:1, genderRequired:false, ageRequired:false, reverse:false, normalRange:{default:[150,400]}, redFlag:{low:50, high:1000}, descriptions:{normal:'피를 멈추게 돕는 수치가 정상 범위에 있어요.', high:'정상 범위보다 다소 높아요.\n검사지와 함께 다시 확인해보세요.', low:'정상 범위보다 다소 낮아요.\n멍이나 출혈이 잦으면 상담을 권해요.', redFlag:'지혈과 관련해 확인이 필요할 수 있어요.\n빠른 시일 내 진료를 권해요.'}, plainExplanation:'피가 났을 때 멈추게 해주는 천연 반창고 역할입니다.'},
  { id:'glucose', name:'공복혈당', unit:'mg/dL', allowedMin:20, allowedMax:800, step:1, genderRequired:false, ageRequired:false, reverse:false, normalRange:{default:[70,99]}, redFlag:{low:50, high:300}, descriptions:{normal:'공복 혈당이 정상 범위에 있어요.', high:'정상 범위보다 다소 높아요.\n식사, 운동, 재검 시점을 함께 봐야 해요.', low:'정상 범위보다 다소 낮아요.\n식은땀이나 어지러움이 있으면 확인이 필요해요.', redFlag:'혈당 확인이 빠르게 필요할 수 있어요.\n빠른 시일 내 진료를 권해요.'}, plainExplanation:'8시간 금식 후 혈액 속 순수한 당분의 양입니다.'},
  { id:'hba1c', name:'HbA1c', unit:'%', allowedMin:3.0, allowedMax:20.0, step:0.1, genderRequired:false, ageRequired:false, reverse:false, normalRange:{default:[0,5.6]}, redFlag:{high:10.0}, descriptions:{normal:'최근 몇 달 평균 혈당 흐름이 좋은 편이에요.', high:'정상 범위보다 다소 높아요.\n생활습관과 재검 계획을 상담해보세요.', low:'보통 낮게 해석하는 항목은 아니에요.\n검사지 단위를 다시 확인해주세요.', redFlag:'혈당 조절 확인이 많이 필요할 수 있어요.\n빠른 시일 내 진료를 권해요.'}, plainExplanation:'지난 2~3달 평균 혈당 성적표입니다.'},
  { id:'totalCholesterol', name:'총콜레스테롤', unit:'mg/dL', allowedMin:50, allowedMax:600, step:1, genderRequired:false, ageRequired:false, reverse:false, normalRange:{default:[0,199]}, redFlag:{}, descriptions:{normal:'전체 콜레스테롤이 기준 범위에 있어요.', high:'정상 범위보다 다소 높아요.\nLDL, HDL, 중성지방과 함께 보는 것이 좋아요.', low:'정상 범위보다 낮게 나왔어요.\n식사 상태나 검사 상황을 확인해보세요.', redFlag:'병원 상담 권장 범위예요.\n의료진과 결과를 함께 확인해주세요.'}, plainExplanation:'혈액 속 전체 기름 성분의 총합계입니다.'},
  { id:'ldl', name:'LDL', unit:'mg/dL', allowedMin:10, allowedMax:400, step:1, genderRequired:false, ageRequired:false, reverse:false, normalRange:{default:[0,129]}, redFlag:{high:190}, descriptions:{normal:'LDL 수치가 기준 범위에 있어요.', high:'정상 범위보다 다소 높아요.\n식사, 운동, 기존 건강상태를 함께 봐야 해요.', low:'낮은 LDL은 보통 문제로 보지 않지만 상황에 따라 달라요.', redFlag:'혈관 건강 확인이 필요할 수 있어요.\n병원 상담을 권해요.'}, plainExplanation:'혈관 벽에 찌꺼기를 쌓는 나쁜 기름입니다.'},
  { id:'hdl', name:'HDL', unit:'mg/dL', allowedMin:10, allowedMax:150, step:1, genderRequired:true, ageRequired:false, reverse:true, normalRange:{male:[40,150], female:[50,150]}, redFlag:{}, descriptions:{normal:'혈관 청소를 돕는 수치가 기준 이상이에요.', high:'HDL은 높을수록 좋은 방향으로 보는 항목이에요.', low:'기준보다 다소 낮아요.\n운동과 생활습관을 함께 점검해보세요.', redFlag:'병원 상담 권장 범위예요.\n의료진과 결과를 함께 확인해주세요.'}, plainExplanation:'혈관 벽을 청소해주는 좋은 기름입니다.'},
  { id:'triglyceride', name:'중성지방', unit:'mg/dL', allowedMin:20, allowedMax:3000, step:1, genderRequired:false, ageRequired:false, reverse:false, normalRange:{default:[0,149]}, redFlag:{high:500}, descriptions:{normal:'중성지방이 기준 범위에 있어요.', high:'정상 범위보다 다소 높아요.\n최근 식사나 음주 영향을 받을 수 있어요.', low:'낮은 수치는 보통 단독으로 크게 보지 않아요.', redFlag:'췌장에 부담이 갈 수 있는 수치예요.\n진료를 권해요.'}, plainExplanation:'고기, 밥, 술을 많이 먹으면 축적되는 잉여 지방입니다.'},
  { id:'ast', name:'AST', unit:'U/L', allowedMin:1, allowedMax:5000, step:1, genderRequired:false, ageRequired:false, reverse:false, normalRange:{default:[0,40]}, redFlag:{high:120}, descriptions:{normal:'간 관련 효소 수치가 기준 안에 있어요.', high:'정상 범위보다 다소 높아요.\n음주, 운동, 약물 영향도 함께 볼 수 있어요.', low:'낮은 AST는 보통 크게 문제 삼지 않아요.', redFlag:'간 상태 확인이 필요할 수 있어요.\n빠른 시일 내 진료를 권해요.'}, plainExplanation:'간세포가 무리를 하면 혈액으로 흘러나오는 물질입니다.'},
  { id:'alt', name:'ALT', unit:'U/L', allowedMin:1, allowedMax:5000, step:1, genderRequired:false, ageRequired:false, reverse:false, normalRange:{default:[0,40]}, redFlag:{high:120}, descriptions:{normal:'간 건강을 보여주는 효소가 기준 안에 있어요.', high:'정상 범위보다 다소 높아요.\n최근 음주나 약 복용을 함께 확인해보세요.', low:'낮은 ALT는 보통 크게 문제 삼지 않아요.', redFlag:'간 상태 확인이 필요할 수 있어요.\n빠른 시일 내 진료를 권해요.'}, plainExplanation:'간 건강을 가장 민감하게 보여주는 대표 효소입니다.'},
  { id:'ggtp', name:'γ-GTP', unit:'U/L', allowedMin:1, allowedMax:3000, step:1, genderRequired:true, ageRequired:false, reverse:false, normalRange:{male:[0,63], female:[0,35]}, redFlag:{maleHigh:150, femaleHigh:100}, descriptions:{normal:'간에 부담을 주는 효소 수치가 기준 안에 있어요.', high:'정상 범위보다 다소 높아요.\n음주나 기름진 식사가 영향을 줄 수 있어요.', low:'낮은 수치는 보통 크게 문제 삼지 않아요.', redFlag:'간이 많이 지쳐 있을 수 있어요.\n진료를 권해요.'}, plainExplanation:'잦은 음주나 기름진 식사로 간이 스트레스를 받을 때 올라갑니다.'},
  { id:'creatinine', name:'크레아티닌', unit:'mg/dL', allowedMin:0.2, allowedMax:20, step:0.1, genderRequired:true, ageRequired:false, reverse:false, normalRange:{male:[0.7,1.4], female:[0.5,1.2]}, redFlag:{maleHigh:2.0, femaleHigh:1.5}, descriptions:{normal:'콩팥 청소 기능을 보는 수치가 기준 안에 있어요.', high:'정상 범위보다 다소 높아요.\n수분 상태와 근육량 영향을 함께 봐야 해요.', low:'정상 범위보다 낮아요.\n체격이나 근육량에 따라 달라질 수 있어요.', redFlag:'콩팥 기능 확인이 필요할 수 있어요.\n빠른 시일 내 진료를 권해요.'}, plainExplanation:'근육 활동 후 남은 찌꺼기로, 콩팥이 약해지면 쌓입니다.'},
  { id:'bun', name:'BUN', unit:'mg/dL', allowedMin:1, allowedMax:200, step:1, genderRequired:false, ageRequired:false, reverse:false, normalRange:{default:[8,24]}, redFlag:{high:60}, descriptions:{normal:'노폐물 수치가 기준 범위에 있어요.', high:'정상 범위보다 다소 높아요.\n수분 섭취나 단백질 섭취 영향도 볼 수 있어요.', low:'정상 범위보다 낮아요.\n식사 상태를 함께 확인해보세요.', redFlag:'콩팥 기능이나 탈수 확인이 필요할 수 있어요.\n진료를 권해요.'}, plainExplanation:'단백질이 분해되고 남은 노폐물로 콩팥의 청소 능력을 측정합니다.'}
];
